channel_sources:
  - pytorch
  - conda-forge
  - defaults

package_name:
  - inferno
  - inferno-cpu
pytorch_flavor:
  - pytorch
  - pytorch-cpu
torchvision_flavor:
  - torchvision
  - torchvision-cpu
zip_keys:
  - package_name
  - pytorch_flavor
  - torchvision_flavor
pytorch_pinning:
  - ">=1.0,<1.1"
torchvision_pinning:
  - ">=0.2,<0.3"
